USE customer_churn_analysis;

SELECT COUNT(*) AS current_rows
FROM services;

INSERT INTO services (
    service_id,
    customer_id,
    customer_count,
    quarter,
    referred_a_friend,
    number_of_referrals,
    tenure_in_months,
    offer,
    phone_service,
    avg_monthly_long_distance_charges,
    multiple_lines,
    internet_service,
    internet_type,
    avg_monthly_gb_download,
    online_security,
    online_backup,
    device_protection_plan,
    premium_tech_support,
    streaming_tv,
    streaming_movies,
    streaming_music,
    unlimited_data,
    contract,
    paperless_billing,
    payment_method,
    monthly_charge,
    total_charges,
    total_refunds,
    total_extra_data_charges,
    total_long_distance_charges,
    total_revenue
)
SELECT
    service_id,
    customer_id,
    CAST(customer_count AS UNSIGNED),
    quarter,
    referred_a_friend,
    CAST(number_of_referrals AS UNSIGNED),
    CAST(tenure_in_months AS UNSIGNED),
    offer,
    phone_service,
    CAST(avg_monthly_long_distance_charges AS DECIMAL(10, 2)),
    multiple_lines,
    internet_service,
    internet_type,
    CAST(avg_monthly_gb_download AS UNSIGNED),
    online_security,
    online_backup,
    device_protection_plan,
    premium_tech_support,
    streaming_tv,
    streaming_movies,
    streaming_music,
    unlimited_data,
    contract,
    paperless_billing,
    payment_method,
    CAST(monthly_charge AS DECIMAL(10, 2)),
    CAST(total_charges AS DECIMAL(12, 2)),
    CAST(total_refunds AS DECIMAL(12, 2)),
    CAST(total_extra_data_charges AS DECIMAL(12, 2)),
    CAST(total_long_distance_charges AS DECIMAL(12, 2)),
    CAST(total_revenue AS DECIMAL(12, 2))
FROM services_staging;
